### ISSUE TITLE
Encounter error when using github action microsoft/setup-msstore-cli@v1

### ISSUE THREAD

**Issue by yong-soon** [microsoft/setup-msstore-cli#133]
I am getting the following error on the .Net Framework not being detected when using the github action

Run msstore reconfigure --tenantId *** --sellerId *** --clientId *** --clientSecret ***
You must install or update .NET to run this application.

Framework: 'Microsoft.NETCore.App', version '8.0.0' (x64)

![image](https://github.com/microsoft/setup-msstore-cli/assets/59637618/22c332ed-6565-4321-aca9-fc62cc51c754)

**Comment by azchohfi** [comment]
By default, the setup task picks up the latest version of the tool, and it just got updated with dotnet 8. You have to add the setup dotnet task before this task:
```yaml
- uses: actions/setup-dotnet@v3
  with:
    dotnet-version: '8.0.x'
```
The agents haven't been updated yet, so you need this until they have it installed by default.
